version: '2.1'
services:
  server:
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: npm run dev
    env_file:
      - ./dev.env
    depends_on:
      mongo:
          condition: service_healthy
      rabbitmq:
          condition: service_healthy  
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    healthcheck:
     test: exit 0
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:alpine
    ports:
      - 5672:5672
    healthcheck:
      test: exit 0    


