// Folders
const UPLOADS_FOLDER = 'uploads';
const RESIZED_PHOTO_FOLDER = 'instants';

const PUBLIC_PHOTO_FOLDER = 'photos';
const PUBLIC_ORIGINAL_PHOTO_FOLDER = 'photos-original';

// Instant
const INSTANT_STATUS = {
  PENDING: 'Pending',
  DONE: 'Done',
};
const DEFAULT_RESIZED_WIDTH = 140;
const DEFAULT_RESIZED_HEIGHT = 140;

module.exports = {
  PUBLIC_PHOTO_FOLDER,
  RESIZED_PHOTO_FOLDER,
  UPLOADS_FOLDER,
  INSTANT_STATUS,
  PUBLIC_ORIGINAL_PHOTO_FOLDER,
  DEFAULT_RESIZED_WIDTH,
  DEFAULT_RESIZED_HEIGHT,
};
